DEFAULT_USER_AVATAR = (
    'http://www.33lc.com/uploadfile/2013/0723/20130723025619512.png')

RECAPTCHA_USE_SSL = False
RECAPTCHA_PUBLIC_KEY = 'SAAAAAPLmScrvpFrjiCgEA9X85rlOYoFK'
RECAPTCHA_PRIVATE_KEY = 'SAAAAACMROyNO4rBbEVT3lYcjkQdpLdSC'
ENABLE_BABEL = True
BABEL_DEFAULT_LOCALE = 'zh_CN.UTF-8'
BABEL_DEFAULT_TIMEZONE = 'UTC+8'
ENABLE_MAIL = True
DEFAULT_MAIL_SENDER = 'hello@transflow.com'
